spring.application.name=GameLib
server.port=9000

# Configuração do Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:gamelibdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console Web do H2 (Acesse via http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de API Externa (RAWG API)
rawg.api.url=https://api.rawg.io/api
rawg.api.key=7a9a038e26624ddda7056a745197320c

# JWT Configuration (Chave com no mínimo 256 bits/32 caracteres para algoritmo HMAC-SHA)
api.security.token.secret=4zY9&kL2#mP8$vQ1!xR5@wT7*jN3^bX6
api.security.token.expiration-ms=86400000
